name: Calculator API Pipeline

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
           node-version: 16
      - run: npm ci
      - run: npm prettier
      - run: npm prettier:fix
      - run: npm run lint

      - name: Super Linter
        uses: super-linter/super-linter@v5
        with:
          full-depth: 0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
