name: Calculator API Pipeline

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super Linter
        uses: super-linter/super-linter@v5
        with:
          full-depth: 0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
