name: Calculator API Pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run prettier

      - name: Prettier Fix
        run: npm run prettier:fix
      - name: Run lint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Build, tag, and push image to AWS ECR
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: "calculator-api"
          IMAGE_TAG: ${{github.sha}}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c0q1q5p8
          docker build -t calculator-api .
          docker tag calculator-api:latest public.ecr.aws/c0q1q5p8/calculator-api:latest
          docker push public.ecr.aws/c0q1q5p8/calculator-api:latest


